// BDDlexique.js — Français Master
// 243 mots avec phonétique pour anglophones 40+
// Généré à partir des questions & leçons du quiz

const LEXIQUE_BDD = [
  {fr:"à",en:"to / at / in",phon:"*ah*",def:"Préposition de lieu ou de temps.",ex:"Je vais à Paris.",level:1,cat:"préposition"},
  {fr:"a",en:"has",phon:"*ah*",def:"Troisième personne du singulier du verbe avoir.",ex:"Elle a une voiture.",level:5,cat:"verbe"},
  {fr:"acheter",en:"to buy",phon:"*ash-TAY*",def:"Acquérir contre de l'argent.",ex:"J'achète du pain.",level:2,cat:"verbe"},
  {fr:"adresse",en:"address",phon:"*a-DRESS*",def:"Lieu où habite une personne.",ex:"Quelle est votre adresse ?",level:4,cat:"nom"},
  {fr:"aider",en:"to help",phon:"*ay-DAY*",def:"Apporter son soutien.",ex:"Pouvez-vous m'aider ?",level:4,cat:"verbe"},
  {fr:"aller",en:"to go",phon:"*a-LAY*",def:"Se déplacer vers un endroit.",ex:"Je vais au marché.",level:1,cat:"verbe"},
  {fr:"ami",en:"friend (male)",phon:"*a-MEE*",def:"Personne avec qui on a des liens d'affection.",ex:"C'est mon ami Pierre.",level:3,cat:"social"},
  {fr:"amie",en:"friend (female)",phon:"*a-MEE*",def:"Personne avec qui on a des liens d'affection.",ex:"C'est mon amie Marie.",level:3,cat:"social"},
  {fr:"après",en:"after",phon:"*a-PRAY*",def:"Plus tard dans le temps.",ex:"Après le déjeuner.",level:2,cat:"préposition"},
  {fr:"après-demain",en:"the day after tomorrow",phon:"*a-PRAY duh-MAN*",def:"Deux jours après aujourd'hui.",ex:"À après-demain !",level:4,cat:"temps"},
  {fr:"arbre",en:"tree",phon:"*AR-bruh*",def:"Grande plante ligneuse.",ex:"Un cerisier dans le jardin.",level:3,cat:"nature"},
  {fr:"arroser",en:"to water",phon:"*a-ro-ZAY*",def:"Donner de l'eau aux plantes.",ex:"Arroser les fleurs.",level:3,cat:"verbe"},
  {fr:"arrosoir",en:"watering can",phon:"*a-ro-ZWAHR*",def:"Récipient pour arroser.",ex:"Remplir l'arrosoir.",level:3,cat:"outil"},
  {fr:"au",en:"at the / to the",phon:"*oh*",def:"Contraction de 'à le'.",ex:"Je vais au cinéma.",level:1,cat:"préposition"},
  {fr:"au revoir",en:"goodbye",phon:"*oh ruh-VWAHR*",def:"Formule de départ.",ex:"Au revoir et à bientôt.",level:1,cat:"salutation"},
  {fr:"aujourd'hui",en:"today",phon:"*o-zhor-DWEE*",def:"Le jour présent.",ex:"Aujourd'hui, il fait beau.",level:4,cat:"temps"},
  {fr:"automne",en:"autumn",phon:"*o-TON*",def:"Saison après l'été.",ex:"En automne, les feuilles tombent.",level:4,cat:"saison"},
  {fr:"avec",en:"with",phon:"*a-VEK*",def:"En compagnie de.",ex:"Je sors avec des amis.",level:1,cat:"préposition"},
  {fr:"baguette",en:"baguette",phon:"*ba-GET*",def:"Pain long et croustillant.",ex:"Une baguette tradition.",level:2,cat:"aliment"},
  {fr:"beau",en:"beautiful / nice",phon:"*bo*",def:"Qui plaît à la vue.",ex:"Il fait beau.",level:1,cat:"adjectif"},
  {fr:"beaucoup",en:"a lot",phon:"*bo-KOO*",def:"En grande quantité.",ex:"Merci beaucoup.",level:1,cat:"adverbe"},
  {fr:"bien",en:"well / good",phon:"*byan*",def:"De manière satisfaisante.",ex:"Je vais bien.",level:1,cat:"adverbe"},
  {fr:"bientôt",en:"soon",phon:"*byan-TO*",def:"Dans un futur proche.",ex:"À bientôt !",level:2,cat:"temps"},
  {fr:"bonjour",en:"good morning / hello",phon:"*bon-ZHOOR*",def:"Salutation du matin et de la journée.",ex:"Bonjour, Madame.",level:1,cat:"salutation"},
  {fr:"bonne nuit",en:"good night",phon:"*bon NUH-ee*",def:"Souhait avant de dormir.",ex:"Bonne nuit, les enfants.",level:1,cat:"salutation"},
  {fr:"bonsoir",en:"good evening",phon:"*bon-SWAHR*",def:"Salutation du soir.",ex:"Bonsoir, comment allez-vous ?",level:1,cat:"salutation"},
  {fr:"boucherie",en:"butcher shop",phon:"*boo-shuh-REE*",def:"Magasin où l'on vend de la viande.",ex:"Aller à la boucherie.",level:3,cat:"commerce"},
  {fr:"boulangerie",en:"bakery",phon:"*boo-lan-zhree*",def:"Magasin de pain et viennoiseries.",ex:"La boulangerie du coin.",level:2,cat:"commerce"},
  {fr:"bruit",en:"noise",phon:"*bw-ee*",def:"Son désagréable.",ex:"Il y a trop de bruit.",level:3,cat:"sensation"},
  {fr:"c'est",en:"it is / that is",phon:"*say*",def:"Forme contractée de 'ce est'.",ex:"C'est un bon restaurant.",level:1,cat:"expression"},
  {fr:"ça",en:"that / it",phon:"*sah*",def:"Pronom démonstratif.",ex:"Ça va bien.",level:1,cat:"pronom"},
  {fr:"café",en:"coffee / café",phon:"*ka-FAY*",def:"Boisson ou établissement.",ex:"Je prends un café.",level:1,cat:"aliment"},
  {fr:"calme",en:"quiet / calm",phon:"*kalm*",def:"Absence d'agitation.",ex:"Le calme du quartier.",level:3,cat:"adjectif"},
  {fr:"cent",en:"hundred",phon:"*son*",def:"Nombre 100.",ex:"Cent euros.",level:5,cat:"nombre"},
  {fr:"cependant",en:"however",phon:"*suh-pan-DAN*",def:"Mais, pourtant.",ex:"Cependant, je ne suis pas d'accord.",level:6,cat:"conjonction"},
  {fr:"cerise",en:"cherry",phon:"*suh-REEZ*",def:"Petit fruit rouge.",ex:"Une livre de cerises.",level:2,cat:"aliment"},
  {fr:"certain",en:"certain / some",phon:"*ser-TAN*",def:"Qui ne fait pas de doute.",ex:"Un certain charme.",level:5,cat:"adjectif"},
  {fr:"champ",en:"field",phon:"*shon*",def:"Espace de terre cultivée.",ex:"Les champs de blé.",level:4,cat:"nature"},
  {fr:"changer",en:"to change",phon:"*shon-ZHAY*",def:"Rendre différent.",ex:"Changer de chemise.",level:4,cat:"verbe"},
  {fr:"charcuterie",en:"delicatessen",phon:"*shar-koo-tuh-REE*",def:"Magasin de produits à base de viande.",ex:"Du jambon à la charcuterie.",level:3,cat:"commerce"},
  {fr:"chaud",en:"hot",phon:"*sho*",def:"À température élevée.",ex:"Il fait chaud.",level:3,cat:"adjectif"},
  {fr:"cher",en:"expensive / dear",phon:"*shair*",def:"Qui coûte beaucoup.",ex:"C'est trop cher.",level:2,cat:"adjectif"},
  {fr:"chercher",en:"to look for",phon:"*shair-SHAY*",def:"Essayer de trouver.",ex:"Je cherche mes clés.",level:2,cat:"verbe"},
  {fr:"chez",en:"at the house of",phon:"*shay*",def:"Préposition de lieu.",ex:"Je vais chez mon ami.",level:3,cat:"préposition"},
  {fr:"chose",en:"thing",phon:"*shoz*",def:"Objet ou concept.",ex:"Une chose importante.",level:2,cat:"nom"},
  {fr:"combien",en:"how much",phon:"*kom-BYAN*",def:"Quelle quantité.",ex:"Ça fait combien ?",level:2,cat:"adverbe interrogatif"},
  {fr:"comment",en:"how",phon:"*ko-MON*",def:"De quelle manière.",ex:"Comment allez-vous ?",level:1,cat:"adverbe interrogatif"},
  {fr:"comprendre",en:"to understand",phon:"*kom-PRON-druh*",def:"Saisir le sens.",ex:"Je ne comprends pas.",level:2,cat:"verbe"},
  {fr:"connaître",en:"to know (people/places)",phon:"*ko-NE-truh*",def:"Avoir une relation avec.",ex:"Je connais Paris.",level:4,cat:"verbe"},
  {fr:"croissant",en:"croissant",phon:"*krwa-SAN*",def:"Viennoiserie en forme de croissant.",ex:"Un croissant au beurre.",level:2,cat:"aliment"},
  {fr:"cuisine",en:"kitchen / cooking",phon:"*kwee-ZEEN*",def:"Pièce ou art culinaire.",ex:"La cuisine française.",level:3,cat:"lieu"},
  {fr:"dans",en:"in / inside",phon:"*don*",def:"Préposition de lieu.",ex:"Dans la maison.",level:1,cat:"préposition"},
  {fr:"de",en:"of / from",phon:"*duh*",def:"Préposition de provenance ou possession.",ex:"Un verre de vin.",level:1,cat:"préposition"},
  {fr:"demain",en:"tomorrow",phon:"*duh-MAN*",def:"Le jour suivant.",ex:"À demain !",level:2,cat:"temps"},
  {fr:"demander",en:"to ask",phon:"*duh-mon-DAY*",def:"Poser une question.",ex:"Je demande le chemin.",level:2,cat:"verbe"},
  {fr:"dentiste",en:"dentist",phon:"*don-TEEST*",def:"Médecin des dents.",ex:"Prendre rendez-vous chez le dentiste.",level:5,cat:"profession"},
  {fr:"dépenser",en:"to spend",phon:"*day-pon-SAY*",def:"Utiliser de l'argent.",ex:"Ne pas trop dépenser.",level:4,cat:"verbe"},
  {fr:"désolé",en:"sorry",phon:"*day-zo-LAY*",def:"Qui exprime des regrets.",ex:"Je suis désolé.",level:2,cat:"adjectif"},
  {fr:"devoir",en:"must / to have to",phon:"*duh-VWAHR*",def:"Obligation.",ex:"Je dois partir.",level:3,cat:"verbe"},
  {fr:"dire",en:"to say",phon:"*deer*",def:"Exprimer avec des mots.",ex:"Comment dit-on en français ?",level:2,cat:"verbe"},
  {fr:"donc",en:"so / therefore",phon:"*donk*",def:"Marque de conséquence.",ex:"Il pleut, donc je reste.",level:4,cat:"conjonction"},
  {fr:"donner",en:"to give",phon:"*do-NAY*",def:"Offrir quelque chose.",ex:"Donnez-moi la main.",level:2,cat:"verbe"},
  {fr:"douzaine",en:"dozen",phon:"*doo-ZEN*",def:"Ensemble de douze.",ex:"Une douzaine d'œufs.",level:2,cat:"quantité"},
  {fr:"droit",en:"right / straight",phon:"*drwah*",def:"Côté opposé à gauche.",ex:"Tournez à droite.",level:4,cat:"direction"},
  {fr:"du",en:"some (masculine)",phon:"*dew*",def:"Article partitif.",ex:"Du fromage.",level:1,cat:"article"},
  {fr:"eau",en:"water",phon:"*oh*",def:"Liquide transparent.",ex:"Un verre d'eau.",level:1,cat:"aliment"},
  {fr:"église",en:"church",phon:"*ay-GLEEZ*",def:"Édifice religieux.",ex:"L'église du village.",level:4,cat:"lieu"},
  {fr:"emprunter",en:"to borrow",phon:"*om-prun-TAY*",def:"Prendre temporairement.",ex:"Emprunter un livre.",level:3,cat:"verbe"},
  {fr:"en",en:"in / by / some",phon:"*on*",def:"Préposition ou pronom.",ex:"J'en veux.",level:1,cat:"préposition"},
  {fr:"enchanté",en:"nice to meet you (male)",phon:"*on-shon-TAY*",def:"Formule de politesse.",ex:"Enchanté, je suis Pierre.",level:1,cat:"salutation"},
  {fr:"enchantée",en:"nice to meet you (female)",phon:"*on-shon-TAY*",def:"Formule de politesse.",ex:"Enchantée, je suis Marie.",level:1,cat:"salutation"},
  {fr:"enfant",en:"child",phon:"*on-FAN*",def:"Jeune personne.",ex:"Les enfants jouent.",level:3,cat:"personne"},
  {fr:"envie",en:"desire",phon:"*on-VEE*",def:"Souhait.",ex:"J'ai envie de dormir.",level:2,cat:"nom"},
  {fr:"erreur",en:"mistake",phon:"*eh-REUR*",def:"Action incorrecte.",ex:"Corriger une erreur.",level:4,cat:"nom"},
  {fr:"essayer",en:"to try",phon:"*eh-say-YAY*",def:"Tenter.",ex:"Essayer de parler français.",level:3,cat:"verbe"},
  {fr:"et",en:"and",phon:"*ay*",def:"Conjonction de coordination.",ex:"Toi et moi.",level:1,cat:"conjonction"},
  {fr:"été",en:"summer",phon:"*ay-TAY*",def:"Saison chaude.",ex:"En été, il fait chaud.",level:3,cat:"saison"},
  {fr:"être",en:"to be",phon:"*E-truh*",def:"Verbe d'état.",ex:"Je suis fatigué.",level:1,cat:"verbe"},
  {fr:"étudier",en:"to study",phon:"*ay-tew-DYAY*",def:"Apprendre.",ex:"Étudier le français.",level:4,cat:"verbe"},
  {fr:"excusez-moi",en:"excuse me",phon:"*ek-skew-zay-MWAH*",def:"Formule pour s'excuser.",ex:"Excusez-moi, l'heure ?",level:1,cat:"politesse"},
  {fr:"faire",en:"to do / to make",phon:"*fair*",def:"Réaliser une action.",ex:"Je fais du sport.",level:1,cat:"verbe"},
  {fr:"fatigué",en:"tired",phon:"*fa-tee-GAY*",def:"Qui a besoin de repos.",ex:"Je suis fatigué.",level:3,cat:"adjectif"},
  {fr:"faucher",en:"to mow",phon:"*fo-SHAY*",def:"Couper l'herbe.",ex:"Faucher la pelouse.",level:3,cat:"verbe"},
  {fr:"femme",en:"woman / wife",phon:"*fam*",def:"Personne de sexe féminin.",ex:"Une femme élégante.",level:1,cat:"personne"},
  {fr:"fenêtre",en:"window",phon:"*fuh-NE-truh*",def:"Ouverture dans un mur.",ex:"Ouvrir la fenêtre.",level:4,cat:"objet"},
  {fr:"fermé",en:"closed",phon:"*fair-MAY*",def:"Opposé d'ouvert.",ex:"Le magasin est fermé.",level:3,cat:"adjectif"},
  {fr:"feuille",en:"leaf",phon:"*fuh-yuh*",def:"Partie verte d'une plante.",ex:"Une feuille d'arbre.",level:3,cat:"nature"},
  {fr:"fleur",en:"flower",phon:"*flur*",def:"Partie colorée d'une plante.",ex:"Une belle fleur.",level:2,cat:"nature"},
  {fr:"fois",en:"time (occasion)",phon:"*fwah*",def:"Occurrence.",ex:"Une fois par semaine.",level:3,cat:"nom"},
  {fr:"frais",en:"cool / fresh",phon:"*fray*",def:"Température modérée.",ex:"Il fait frais.",level:3,cat:"adjectif"},
  {fr:"froid",en:"cold",phon:"*frwah*",def:"Température basse.",ex:"Il fait froid.",level:2,cat:"adjectif"},
  {fr:"fromage",en:"cheese",phon:"*fro-MAHZH*",def:"Produit laitier.",ex:"Du fromage de chèvre.",level:2,cat:"aliment"},
  {fr:"fruit",en:"fruit",phon:"*frwee*",def:"Aliment sucré des plantes.",ex:"Un panier de fruits.",level:2,cat:"aliment"},
  {fr:"gare",en:"train station",phon:"*gar*",def:"Lieu de passage des trains.",ex:"La gare SNCF.",level:4,cat:"lieu"},
  {fr:"gâteau",en:"cake",phon:"*ga-TO*",def:"Pâtisserie sucrée.",ex:"Un gâteau d'anniversaire.",level:2,cat:"aliment"},
  {fr:"gauche",en:"left",phon:"*gosh*",def:"Côté opposé à droite.",ex:"À gauche.",level:4,cat:"direction"},
  {fr:"gentil",en:"kind",phon:"*jon-TEE*",def:"Qui a de la gentillesse.",ex:"Un voisin gentil.",level:3,cat:"adjectif"},
  {fr:"gluten",en:"gluten",phon:"*glu-TEN*",def:"Protéine du blé.",ex:"Sans gluten.",level:3,cat:"aliment"},
  {fr:"grand",en:"big / tall",phon:"*gron*",def:"De taille importante.",ex:"Un grand jardin.",level:2,cat:"adjectif"},
  {fr:"habiter",en:"to live",phon:"*a-bee-TAY*",def:"Résider quelque part.",ex:"J'habite à Paris.",level:1,cat:"verbe"},
  {fr:"haie",en:"hedge",phon:"*ay*",def:"Clôture végétale.",ex:"Tailler la haie.",level:3,cat:"nature"},
  {fr:"heure",en:"hour / time",phon:"*ur*",def:"Unité de temps.",ex:"À quelle heure ?",level:2,cat:"temps"},
  {fr:"heureux",en:"happy",phon:"*uh-RUH*",def:"Content.",ex:"Je suis heureux.",level:3,cat:"adjectif"},
  {fr:"hiver",en:"winter",phon:"*ee-VAIR*",def:"Saison froide.",ex:"En hiver, il neige.",level:3,cat:"saison"},
  {fr:"homme",en:"man",phon:"*om*",def:"Personne de sexe masculin.",ex:"Un homme âgé.",level:1,cat:"personne"},
  {fr:"hôtel",en:"hotel",phon:"*o-TEL*",def:"Établissement d'hébergement.",ex:"Un hôtel confortable.",level:4,cat:"lieu"},
  {fr:"ici",en:"here",phon:"*ee-SEE*",def:"Dans ce lieu.",ex:"Je suis ici.",level:2,cat:"adverbe"},
  {fr:"il",en:"he / it",phon:"*eel*",def:"Pronom sujet masculin.",ex:"Il fait beau.",level:1,cat:"pronom"},
  {fr:"île",en:"island",phon:"*eel*",def:"Terre entourée d'eau.",ex:"L'île de Ré.",level:4,cat:"lieu"},
  {fr:"impasse",en:"dead end",phon:"*om-PASS*",def:"Rue sans issue.",ex:"Habiter dans une impasse.",level:3,cat:"lieu"},
  {fr:"inviter",en:"to invite",phon:"*on-vee-TAY*",def:"Convier quelqu'un.",ex:"Inviter des amis.",level:3,cat:"verbe"},
  {fr:"jardin",en:"garden",phon:"*jar-DAN*",def:"Espace planté.",ex:"Un joli jardin.",level:2,cat:"nature"},
  {fr:"je",en:"I",phon:"*zhuh*",def:"Pronom sujet première personne.",ex:"Je parle français.",level:1,cat:"pronom"},
  {fr:"jeu",en:"game",phon:"*zhuh*",def:"Activité ludique.",ex:"Un jeu de société.",level:4,cat:"nom"},
  {fr:"jeune",en:"young",phon:"*zhun*",def:"D'âge peu avancé.",ex:"Une jeune fille.",level:3,cat:"adjectif"},
  {fr:"joli",en:"pretty",phon:"*zho-LEE*",def:"Agréable à regarder.",ex:"Une jolie fleur.",level:2,cat:"adjectif"},
  {fr:"jour",en:"day",phon:"*zhoor*",def:"Période de 24h.",ex:"Bonjour !",level:1,cat:"temps"},
  {fr:"jusque",en:"until",phon:"*zhoos-KUH*",def:"Marque une limite.",ex:"Jusqu'à demain.",level:4,cat:"préposition"},
  {fr:"là",en:"there",phon:"*lah*",def:"Dans cet endroit.",ex:"Là-bas.",level:2,cat:"adverbe"},
  {fr:"lait",en:"milk",phon:"*lay*",def:"Liquide blanc.",ex:"Du lait cru.",level:2,cat:"aliment"},
  {fr:"laisser",en:"to leave / to let",phon:"*lay-SAY*",def:"Abandonner ou permettre.",ex:"Laissez-moi tranquille.",level:4,cat:"verbe"},
  {fr:"large",en:"wide",phon:"*larzh*",def:"De grande largeur.",ex:"Une rue large.",level:4,cat:"adjectif"},
  {fr:"leçon",en:"lesson",phon:"*luh-SON*",def:"Enseignement.",ex:"Apprendre la leçon.",level:2,cat:"nom"},
  {fr:"légume",en:"vegetable",phon:"*lay-GOOM*",def:"Plante potagère.",ex:"Des légumes frais.",level:2,cat:"aliment"},
  {fr:"lentement",en:"slowly",phon:"*lon-tuh-MON*",def:"À faible vitesse.",ex:"Parlez plus lentement.",level:2,cat:"adverbe"},
  {fr:"lettre",en:"letter",phon:"*LE-truh*",def:"Caractère d'alphabet.",ex:"Écrire une lettre.",level:4,cat:"objet"},
  {fr:"libre",en:"free",phon:"*LEE-bruh*",def:"Disponible.",ex:"Je suis libre ce soir.",level:3,cat:"adjectif"},
  {fr:"livre",en:"book (masculin) / pound (féminin)",phon:"*LEE-vruh*",def:"Ouvrage ou mesure.",ex:"Un livre intéressant.",level:2,cat:"objet"},
  {fr:"long",en:"long",phon:"*lon*",def:"De grande longueur.",ex:"Un long trajet.",level:3,cat:"adjectif"},
  {fr:"lui",en:"him / her",phon:"*lwee*",def:"Pronom personnel.",ex:"Je lui parle.",level:3,cat:"pronom"},
  {fr:"maison",en:"house",phon:"*may-ZON*",def:"Bâtiment d'habitation.",ex:"À la maison.",level:2,cat:"lieu"},
  {fr:"manger",en:"to eat",phon:"*mon-ZHAY*",def:"Ingérer de la nourriture.",ex:"Je mange une pomme.",level:2,cat:"verbe"},
  {fr:"marché",en:"market",phon:"*mar-SHAY*",def:"Lieu de vente.",ex:"Aller au marché.",level:2,cat:"lieu"},
  {fr:"mardi",en:"Tuesday",phon:"*mar-DEE*",def:"Deuxième jour de la semaine.",ex:"Mardi prochain.",level:3,cat:"temps"},
  {fr:"mari",en:"husband",phon:"*ma-REE*",def:"Époux.",ex:"Mon mari est retraité.",level:2,cat:"famille"},
  {fr:"matin",en:"morning",phon:"*ma-TAN*",def:"Début du jour.",ex:"Le matin, je me lève tôt.",level:1,cat:"temps"},
  {fr:"médecin",en:"doctor",phon:"*mayd-SAN*",def:"Professionnel de santé.",ex:"Consulter un médecin.",level:5,cat:"profession"},
  {fr:"merci",en:"thank you",phon:"*mair-SEE*",def:"Remerciement.",ex:"Merci beaucoup.",level:1,cat:"politesse"},
  {fr:"mère",en:"mother",phon:"*mair*",def:"Parente de sexe féminin.",ex:"Ma mère est gentille.",level:2,cat:"famille"},
  {fr:"métro",en:"subway",phon:"*may-TRO*",def:"Transport souterrain.",ex:"Prendre le métro.",level:4,cat:"transport"},
  {fr:"midi",en:"noon",phon:"*mee-DEE*",def:"12 heures.",ex:"À midi.",level:3,cat:"temps"},
  {fr:"mieux",en:"better",phon:"*myuh*",def:"Comparatif de bien.",ex:"Je vais mieux.",level:3,cat:"adverbe"},
  {fr:"minute",en:"minute",phon:"*mee-NOOT*",def:"Unité de temps.",ex:"Dans une minute.",level:3,cat:"temps"},
  {fr:"moins",en:"less",phon:"*mwahn*",def:"Quantité inférieure.",ex:"Moins cher.",level:3,cat:"adverbe"},
  {fr:"mois",en:"month",phon:"*mwah*",def:"Période de 30 jours.",ex:"Le mois prochain.",level:3,cat:"temps"},
  {fr:"monnaie",en:"change / currency",phon:"*mo-NAY*",def:"Pièces et billets.",ex:"Avoir de la monnaie.",level:2,cat:"argent"},
  {fr:"monsieur",en:"sir / mister",phon:"*muh-SYUH*",def:"Titre de civilité.",ex:"Bonjour, Monsieur.",level:1,cat:"politesse"},
  {fr:"montagne",en:"mountain",phon:"*mon-TA-nyuh*",def:"Relief élevé.",ex:"La montagne.",level:4,cat:"nature"},
  {fr:"mordre",en:"to bite",phon:"*mor-druh*",def:"Serrer avec les dents.",ex:"Attention, ça mord.",level:5,cat:"verbe"},
  {fr:"mot",en:"word",phon:"*mo*",def:"Unité de langue.",ex:"Chercher ses mots.",level:2,cat:"langue"},
  {fr:"moyen",en:"average / way",phon:"*mwa-YAN*",def:"Milieu ou méthode.",ex:"Par des moyens simples.",level:4,cat:"nom"},
  {fr:"mur",en:"wall",phon:"*mewr*",def:"Cloison.",ex:"Un mur de pierre.",level:4,cat:"objet"},
  {fr:"neige",en:"snow",phon:"*nezh*",def:"Précipitation blanche.",ex:"Il neige.",level:3,cat:"météo"},
  {fr:"non",en:"no",phon:"*non*",def:"Réponse négative.",ex:"Non, merci.",level:1,cat:"interjection"},
  {fr:"nord",en:"north",phon:"*nor*",def:"Point cardinal.",ex:"Le vent du nord.",level:4,cat:"direction"},
  {fr:"notre",en:"our",phon:"*no-truh*",def:"Adjectif possessif.",ex:"Notre maison.",level:3,cat:"déterminant"},
  {fr:"nourriture",en:"food",phon:"*noo-ree-TOOR*",def:"Ce qu'on mange.",ex:"De la bonne nourriture.",level:2,cat:"aliment"},
  {fr:"nous",en:"we / us",phon:"*noo*",def:"Pronom personnel.",ex:"Nous allons au marché.",level:1,cat:"pronom"},
  {fr:"nouveau",en:"new",phon:"*noo-VO*",def:"Récent.",ex:"Un nouveau voisin.",level:2,cat:"adjectif"},
  {fr:"nuage",en:"cloud",phon:"*nu-AZH*",def:"Masse de vapeur.",ex:"Le ciel est couvert de nuages.",level:4,cat:"météo"},
  {fr:"nuit",en:"night",phon:"*nwee*",def:"Période sans soleil.",ex:"Bonne nuit.",level:1,cat:"temps"},
  {fr:"où",en:"where",phon:"*oo*",def:"Lieu interrogatif.",ex:"Où est la gare ?",level:2,cat:"adverbe interrogatif"},
  {fr:"obtenir",en:"to obtain",phon:"*ob-tuh-REER*",def:"Recevoir.",ex:"Obtenir un renseignement.",level:5,cat:"verbe"},
  {fr:"occupé",en:"busy",phon:"*o-koo-PAY*",def:"Qui n'est pas libre.",ex:"Je suis occupé.",level:3,cat:"adjectif"},
  {fr:"œuf",en:"egg",phon:"*uhf*",def:"Aliment ovale.",ex:"Une douzaine d'œufs.",level:2,cat:"aliment"},
  {fr:"oiseau",en:"bird",phon:"*wa-ZO*",def:"Animal à plumes.",ex:"Les oiseaux chantent.",level:3,cat:"animal"},
  {fr:"on",en:"one / we / they",phon:"*on*",def:"Pronom indéfini.",ex:"On parle français ici.",level:3,cat:"pronom"},
  {fr:"ou",en:"or",phon:"*oo*",def:"Conjonction de choix.",ex:"Thé ou café.",level:1,cat:"conjonction"},
  {fr:"oublier",en:"to forget",phon:"*oo-blee-YAY*",def:"Ne plus se souvenir.",ex:"J'ai oublié mon sac.",level:3,cat:"verbe"},
  {fr:"oui",en:"yes",phon:"*wee*",def:"Réponse affirmative.",ex:"Oui, je veux bien.",level:1,cat:"interjection"},
  {fr:"ouvrir",en:"to open",phon:"*oo-VREER*",def:"Déplacer ce qui ferme.",ex:"Ouvrir la porte.",level:3,cat:"verbe"},
  {fr:"pain",en:"bread",phon:"*pan*",def:"Aliment de base.",ex:"Une baguette de pain.",level:2,cat:"aliment"},
  {fr:"papa",en:"dad",phon:"*pa-PA*",def:"Père (affectueux).",ex:"Bonjour papa.",level:2,cat:"famille"},
  {fr:"papier",en:"paper",phon:"*pa-PYAY*",def:"Matériau pour écrire.",ex:"Une feuille de papier.",level:3,cat:"objet"},
  {fr:"pardon",en:"sorry / excuse me",phon:"*par-DON*",def:"Formule d'excuse.",ex:"Pardon, je n'ai pas compris.",level:2,cat:"politesse"},
  {fr:"parent",en:"parent",phon:"*pa-RON*",def:"Père ou mère.",ex:"Mes parents sont âgés.",level:3,cat:"famille"},
  {fr:"parler",en:"to speak",phon:"*par-LAY*",def:"S'exprimer avec des mots.",ex:"Je parle français.",level:1,cat:"verbe"},
  {fr:"partir",en:"to leave",phon:"*par-TEER*",def:"S'en aller.",ex:"Je pars demain.",level:3,cat:"verbe"},
  {fr:"pas",en:"not / step",phon:"*pa*",def:"Négation.",ex:"Je ne sais pas.",level:1,cat:"adverbe"},
  {fr:"passer",en:"to pass / spend",phon:"*pa-SAY*",def:"Aller au-delà.",ex:"Passer un examen.",level:3,cat:"verbe"},
  {fr:"patience",en:"patience",phon:"*pa-SYONS*",def:"Calme dans l'attente.",ex:"Avoir de la patience.",level:4,cat:"qualité"},
  {fr:"pâtisserie",en:"pastry shop",phon:"*pa-tee-sree*",def:"Magasin de gâteaux.",ex:"Une délicieuse pâtisserie.",level:3,cat:"commerce"},
  {fr:"père",en:"father",phon:"*pair*",def:"Parent masculin.",ex:"Mon père est gentil.",level:2,cat:"famille"},
  {fr:"personne",en:"person",phon:"*pair-SON*",def:"Être humain.",ex:"Une personne âgée.",level:2,cat:"nom"},
  {fr:"petit",en:"small",phon:"*puh-TEE*",def:"De taille réduite.",ex:"Un petit jardin.",level:1,cat:"adjectif"},
  {fr:"peu",en:"little / few",phon:"*puh*",def:"Quantité faible.",ex:"Un peu de sel.",level:2,cat:"adverbe"},
  {fr:"peur",en:"fear",phon:"*pur*",def:"Sentiment de crainte.",ex:"J'ai peur.",level:3,cat:"nom"},
  {fr:"pharmacie",en:"pharmacy",phon:"*far-ma-SEE*",def:"Magasin de médicaments.",ex:"À la pharmacie.",level:3,cat:"commerce"},
  {fr:"phrase",en:"sentence",phon:"*fraz*",def:"Ensemble de mots.",ex:"Une phrase simple.",level:3,cat:"langue"},
  {fr:"pièce",en:"room / coin",phon:"*pyess*",def:"Espace ou monnaie.",ex:"Une pièce de théâtre.",level:3,cat:"nom"},
  {fr:"pierre",en:"stone",phon:"*pyair*",def:"Roche.",ex:"Un mur en pierre.",level:4,cat:"objet"},
  {fr:"plage",en:"beach",phon:"*plazh*",def:"Bord de mer.",ex:"Aller à la plage.",level:4,cat:"lieu"},
  {fr:"plaisir",en:"pleasure",phon:"*play-ZEER*",def:"Satisfaction.",ex:"Avec plaisir.",level:2,cat:"sentiment"},
  {fr:"planter",en:"to plant",phon:"*plon-TAY*",def:"Mettre en terre.",ex:"Planter des tomates.",level:3,cat:"verbe"},
  {fr:"pleuvoir",en:"to rain",phon:"*pluh-VWAHR*",def:"Tomber de l'eau.",ex:"Il pleut.",level:3,cat:"verbe"},
  {fr:"pluie",en:"rain",phon:"*plwee*",def:"Précipitation aqueuse.",ex:"La pluie tombe.",level:3,cat:"météo"},
  {fr:"plus",en:"more / no more",phon:"*ploo*",def:"Comparatif de supériorité.",ex:"Plus de pain.",level:2,cat:"adverbe"},
  {fr:"poche",en:"pocket",phon:"*posh*",def:"Petite cavité.",ex:"Mettre la main dans la poche.",level:4,cat:"objet"},
  {fr:"point",en:"point",phon:"*pwan*",def:"Signe ou endroit.",ex:"À quel point ?",level:4,cat:"nom"},
  {fr:"poire",en:"pear",phon:"*pwar*",def:"Fruit.",ex:"Une poire juteuse.",level:2,cat:"aliment"},
  {fr:"poisson",en:"fish",phon:"*pwa-SON*",def:"Animal aquatique.",ex:"Un poisson frais.",level:3,cat:"aliment"},
  {fr:"pomme",en:"apple",phon:"*pom*",def:"Fruit.",ex:"Une pomme rouge.",level:2,cat:"aliment"},
  {fr:"portable",en:"mobile phone",phon:"*por-TA-bluh*",def:"Téléphone mobile.",ex:"Mon portable sonne.",level:4,cat:"objet"},
  {fr:"porte",en:"door",phon:"*port*",def:"Ouverture.",ex:"Fermer la porte.",level:3,cat:"objet"},
  {fr:"poser",en:"to put / to ask",phon:"*po-ZAY*",def:"Placer ou demander.",ex:"Poser une question.",level:3,cat:"verbe"},
  {fr:"potager",en:"vegetable garden",phon:"*po-ta-ZHAY*",def:"Jardin potager.",ex:"Un grand potager.",level:3,cat:"nature"},
  {fr:"pouvoir",en:"can / to be able to",phon:"*poo-VWAHR*",def:"Avoir la capacité.",ex:"Je peux vous aider.",level:2,cat:"verbe"},
  {fr:"préférer",en:"to prefer",phon:"*pray-fay-RAY*",def:"Avoir une préférence.",ex:"Je préfère le thé.",level:2,cat:"verbe"},
  {fr:"prendre",en:"to take",phon:"*PRON-druh*",def:"Saisir.",ex:"Je prends le bus.",level:2,cat:"verbe"},
  {fr:"près",en:"near",phon:"*pray*",def:"À courte distance.",ex:"Près de la maison.",level:3,cat:"préposition"},
  {fr:"prêter",en:"to lend",phon:"*pre-TAY*",def:"Donner temporairement.",ex:"Je te prête mon livre.",level:3,cat:"verbe"},
  {fr:"printemps",en:"spring",phon:"*pran-TON*",def:"Saison après l'hiver.",ex:"Au printemps, les fleurs poussent.",level:3,cat:"saison"},
  {fr:"problème",en:"problem",phon:"*pro-BLEM*",def:"Difficulté.",ex:"Pas de problème.",level:2,cat:"nom"},
  {fr:"prochain",en:"next",phon:"*pro-SHAN*",def:"Qui vient après.",ex:"La semaine prochaine.",level:3,cat:"adjectif"},
  {fr:"prononciation",en:"pronunciation",phon:"*pro-non-see-a-syon*",def:"Manière de dire.",ex:"La prononciation française.",level:4,cat:"langue"},
  {fr:"quand",en:"when",phon:"*kon*",def:"Interrogatif de temps.",ex:"Quand viens-tu ?",level:2,cat:"adverbe interrogatif"},
  {fr:"quartier",en:"neighborhood",phon:"*kar-tyay*",def:"Zone d'une ville.",ex:"Un quartier calme.",level:3,cat:"lieu"},
  {fr:"quel",en:"which / what",phon:"*kel*",def:"Adjectif interrogatif.",ex:"Quel âge as-tu ?",level:2,cat:"adjectif interrogatif"},
  {fr:"quelque",en:"some / a few",phon:"*kel-keuh*",def:"Quantité indéfinie.",ex:"Quelques euros.",level:3,cat:"adjectif indéfini"},
  {fr:"question",en:"question",phon:"*kes-TYON*",def:"Interrogation.",ex:"Poser une question.",level:2,cat:"nom"},
  {fr:"rapide",en:"fast",phon:"*ra-PEED*",def:"Qui va vite.",ex:"Une réponse rapide.",level:4,cat:"adjectif"},
  {fr:"râteau",en:"rake",phon:"*ra-TO*",def:"Outil de jardin.",ex:"Passer le râteau.",level:3,cat:"outil"},
  {fr:"recevoir",en:"to receive",phon:"*ruh-suh-VWAHR*",def:"Obtenir.",ex:"Recevoir un colis.",level:4,cat:"verbe"},
  {fr:"récolter",en:"to harvest",phon:"*ray-kol-TAY*",def:"Cueillir.",ex:"Récolter les légumes.",level:3,cat:"verbe"},
  {fr:"regarder",en:"to watch / to look at",phon:"*ruh-gar-DAY*",def:"Diriger son regard.",ex:"Regarder la télé.",level:2,cat:"verbe"},
  {fr:"remplir",en:"to fill",phon:"*ron-PLEER*",def:"Rendre plein.",ex:"Remplir l'arrosoir.",level:3,cat:"verbe"},
  {fr:"rendez-vous",en:"appointment",phon:"*ron-day-VOO*",def:"Rencontre fixée.",ex:"Prendre un rendez-vous.",level:3,cat:"social"},
  {fr:"répéter",en:"to repeat",phon:"*ray-pay-TAY*",def:"Dire à nouveau.",ex:"Répétez, s'il vous plaît.",level:2,cat:"verbe"},
  {fr:"réponse",en:"answer",phon:"*ray-PONS*",def:"Ce qu'on répond.",ex:"Bonne réponse.",level:2,cat:"nom"},
  {fr:"restaurant",en:"restaurant",phon:"*res-to-ron*",def:"Lieu où l'on mange.",ex:"Au restaurant.",level:2,cat:"lieu"},
  {fr:"retraité",en:"retired (male)",phon:"*ruh-treh-TAY*",def:"Qui a cessé de travailler.",ex:"Il est retraité.",level:1,cat:"personne"},
  {fr:"retraitée",en:"retired (female)",phon:"*ruh-treh-TAY*",def:"Qui a cessé de travailler.",ex:"Elle est retraitée.",level:1,cat:"personne"},
  {fr:"retrouver",en:"to meet up / find again",phon:"*ruh-troo-VAY*",def:"Rencontrer de nouveau.",ex:"On se retrouve au café.",level:3,cat:"verbe"},
  {fr:"réussir",en:"to succeed",phon:"*rayoo-SEER*",def:"Obtenir un bon résultat.",ex:"Réussir son examen.",level:4,cat:"verbe"},
  {fr:"rêver",en:"to dream",phon:"*re-VAY*",def:"Faire des rêves.",ex:"Je rêve de voyager.",level:3,cat:"verbe"},
  {fr:"rire",en:"to laugh",phon:"*reer*",def:"Manifester de la gaieté.",ex:"Faire rire.",level:4,cat:"verbe"},
  {fr:"robe",en:"dress",phon:"*rob*",def:"Vêtement.",ex:"Une robe élégante.",level:4,cat:"vêtement"},
  {fr:"rue",en:"street",phon:"*roo*",def:"Voie publique.",ex:"Une rue piétonne.",level:2,cat:"lieu"},
  {fr:"s'il vous plaît",en:"please (formal)",phon:"*seel voo PLEH*",def:"Formule de politesse.",ex:"Un café, s'il vous plaît.",level:1,cat:"politesse"},
  {fr:"sable",en:"sand",phon:"*sa-bluh*",def:"Petites particules.",ex:"Le sable de la plage.",level:4,cat:"nature"},
  {fr:"saison",en:"season",phon:"*say-ZON*",def:"Période de l'année.",ex:"Les quatre saisons.",level:3,cat:"temps"},
  {fr:"salle",en:"room",phon:"*sal*",def:"Pièce.",ex:"Salle de bain.",level:3,cat:"lieu"},
  {fr:"salut",en:"hi / bye",phon:"*sa-LU*",def:"Salutation informelle.",ex:"Salut, ça va ?",level:1,cat:"salutation"},
  {fr:"santé",en:"health",phon:"*son-TAY*",def:"État physique.",ex:"À votre santé !",level:3,cat:"nom"},
  {fr:"savoir",en:"to know (fact)",phon:"*sa-VWAHR*",def:"Connaître une information.",ex:"Je sais où c'est.",level:3,cat:"verbe"},
  {fr:"se",en:"oneself",phon:"*suh*",def:"Pronom réfléchi.",ex:"Il se lève.",level:3,cat:"pronom"},
  {fr:"semaine",en:"week",phon:"*suh-MEN*",def:"Sept jours.",ex:"La semaine prochaine.",level:2,cat:"temps"},
  {fr:"sentir",en:"to feel / to smell",phon:"*son-TEER*",def:"Percevoir par les sens.",ex:"Je sens bon.",level:4,cat:"verbe"},
  {fr:"serre",en:"greenhouse",phon:"*sair*",def:"Structure vitrée.",ex:"Une serre à tomates.",level:3,cat:"nature"},
  {fr:"service",en:"service / favor",phon:"*sair-VEESS*",def:"Action rendue.",ex:"Rendre service.",level:3,cat:"nom"},
  {fr:"seul",en:"alone",phon:"*suhl*",def:"Sans compagnie.",ex:"Je suis seul.",level:3,cat:"adjectif"},
  {fr:"si",en:"if / so / yes (contradiction)",phon:"*see*",def:"Condition ou affirmation.",ex:"Si, je veux bien.",level:3,cat:"conjonction"},
  {fr:"sœur",en:"sister",phon:"*sur*",def:"Parente féminine.",ex:"Ma sœur cadette.",level:2,cat:"famille"},
  {fr:"soif",en:"thirst",phon:"*swaf*",def:"Besoin de boire.",ex:"J'ai soif.",level:3,cat:"sensation"},
  {fr:"soir",en:"evening",phon:"*swar*",def:"Fin de journée.",ex:"Bonsoir.",level:1,cat:"temps"},
  {fr:"soleil",en:"sun",phon:"*so-LAY*",def:"Astre du jour.",ex:"Il fait du soleil.",level:2,cat:"nature"},
  {fr:"sortir",en:"to go out",phon:"*sor-TEER*",def:"Quitter un lieu.",ex:"Sortir avec des amis.",level:3,cat:"verbe"},
  {fr:"soupe",en:"soup",phon:"*soop*",def:"Potage.",ex:"Une soupe chaude.",level:3,cat:"aliment"},
  {fr:"sourire",en:"smile",phon:"*soo-REER*",def:"Expression heureuse.",ex:"Faire un sourire.",level:4,cat:"verbe"},
  {fr:"souvent",en:"often",phon:"*soo-VON*",def:"Fréquemment.",ex:"Je viens souvent.",level:3,cat:"adverbe"},
  {fr:"spécial",en:"special",phon:"*spay-SYAL*",def:"Hors du commun.",ex:"Un jour spécial.",level:4,cat:"adjectif"},
  {fr:"sucre",en:"sugar",phon:"*soo-kruh*",def:"Substance sucrée.",ex:"Un peu de sucre.",level:3,cat:"aliment"},
  {fr:"sud",en:"south",phon:"*sood*",def:"Point cardinal.",ex:"Le vent du sud.",level:4,cat:"direction"},
  {fr:"suisse",en:"Swiss",phon:"*sweess*",def:"De Suisse.",ex:"Un fromage suisse.",level:4,cat:"adjectif"},
  {fr:"sujet",en:"subject",phon:"*soo-JAY*",def:"Thème.",ex:"Changer de sujet.",level:4,cat:"nom"},
  {fr:"sympa",en:"nice / friendly",phon:"*sam-pa*",def:"Abréviation de sympathique.",ex:"Un voisin sympa.",level:3,cat:"adjectif"},
  {fr:"table",en:"table",phon:"*ta-bluh*",def:"Meuble.",ex:"Mettre la table.",level:2,cat:"objet"},
  {fr:"tailler",en:"to prune",phon:"*ta-YAY*",def:"Couper les branches.",ex:"Tailler la haie.",level:3,cat:"verbe"},
  {fr:"tard",en:"late",phon:"*tar*",def:"Après l'heure habituelle.",ex:"Il est tard.",level:3,cat:"adverbe"},
  {fr:"téléphone",en:"telephone",phon:"*tay-lay-FON*",def:"Appareil de communication.",ex:"Un téléphone portable.",level:4,cat:"objet"},
  {fr:"temps",en:"time / weather",phon:"*ton*",def:"Durée ou climat.",ex:"Il fait beau temps.",level:2,cat:"nom"},
  {fr:"tente",en:"tent",phon:"*tont*",def:"Abri de camping.",ex:"Monter la tente.",level:4,cat:"objet"},
  {fr:"terminer",en:"to finish",phon:"*tair-mee-NAY*",def:"Achever.",ex:"Terminer le travail.",level:3,cat:"verbe"},
  {fr:"terre",en:"earth / ground",phon:"*tair*",def:"Sol.",ex:"La terre du jardin.",level:2,cat:"nature"},
  {fr:"tête",en:"head",phon:"*tet*",def:"Partie supérieure du corps.",ex:"Avoir mal à la tête.",level:3,cat:"corps"},
  {fr:"timbre",en:"stamp",phon:"*TAN-bruh*",def:"Vignette postale.",ex:"Un carnet de timbres.",level:3,cat:"objet"},
  {fr:"tôt",en:"early",phon:"*to*",def:"Avant l'heure.",ex:"Se lever tôt.",level:3,cat:"adverbe"},
  {fr:"toujours",en:"always",phon:"*too-ZHOOR*",def:"À chaque fois.",ex:"Toujours poli.",level:3,cat:"adverbe"},
  {fr:"tourner",en:"to turn",phon:"*toor-NAY*",def:"Changer de direction.",ex:"Tourner à gauche.",level:3,cat:"verbe"},
  {fr:"tous",en:"all (masculine)",phon:"*too*",def:"Totalité.",ex:"Tous les jours.",level:3,cat:"adjectif indéfini"},
  {fr:"tout",en:"all / everything",phon:"*too*",def:"Totalité.",ex:"C'est tout.",level:1,cat:"adjectif indéfini"},
  {fr:"tranche",en:"slice",phon:"*tronsh*",def:"Partie coupée.",ex:"Une tranche de pain.",level:2,cat:"quantité"},
  {fr:"travailler",en:"to work",phon:"*tra-va-YAY*",def:"Exercer une activité.",ex:"Travailler dans un bureau.",level:2,cat:"verbe"},
  {fr:"très",en:"very",phon:"*tray*",def:"Marque d'intensité.",ex:"Très bien.",level:1,cat:"adverbe"},
  {fr:"triste",en:"sad",phon:"*treest*",def:"Attristé.",ex:"Je suis triste.",level:3,cat:"adjectif"},
  {fr:"trois",en:"three",phon:"*trwah*",def:"Nombre.",ex:"Trois euros.",level:2,cat:"nombre"},
  {fr:"trop",en:"too much",phon:"*tro*",def:"Excès.",ex:"Trop de bruit.",level:2,cat:"adverbe"},
  {fr:"trouver",en:"to find",phon:"*troo-VAY*",def:"Découvrir.",ex:"Je trouve mes clés.",level:2,cat:"verbe"},
  {fr:"tu",en:"you (informal)",phon:"*tew*",def:"Pronom sujet singulier.",ex:"Tu parles français.",level:1,cat:"pronom"},
  {fr:"un",en:"one / a (masculine)",phon:"*uh*",def:"Article indéfini.",ex:"Un homme.",level:1,cat:"article"},
  {fr:"une",en:"one / a (feminine)",phon:"*oon*",def:"Article indéfini.",ex:"Une femme.",level:1,cat:"article"},
  {fr:"utile",en:"useful",phon:"*oo-TEEL*",def:"Qui sert à quelque chose.",ex:"Un outil utile.",level:4,cat:"adjectif"},
  {fr:"vache",en:"cow",phon:"*vash*",def:"Animal domestique.",ex:"Une vache dans le pré.",level:3,cat:"animal"},
  {fr:"vacances",en:"holidays",phon:"*va-KONS*",def:"Période de repos.",ex:"Les grandes vacances.",level:3,cat:"temps"},
  {fr:"vendre",en:"to sell",phon:"*von-druh*",def:"Céder contre argent.",ex:"Vendre sa voiture.",level:3,cat:"verbe"},
  {fr:"vent",en:"wind",phon:"*von*",def:"Air en mouvement.",ex:"Il fait du vent.",level:3,cat:"météo"},
  {fr:"verbe",en:"verb",phon:"*verb*",def:"Mot d'action.",ex:"Conjuguer un verbe.",level:3,cat:"grammaire"},
  {fr:"vert",en:"green",phon:"*vair*",def:"Couleur.",ex:"Une pomme verte.",level:2,cat:"couleur"},
  {fr:"vêtement",en:"clothing",phon:"*vet-mong*",def:"Habit.",ex:"Changer de vêtement.",level:4,cat:"vêtement"},
  {fr:"viande",en:"meat",phon:"*vee-and*",def:"Chair animale.",ex:"De la viande rouge.",level:2,cat:"aliment"},
  {fr:"vide",en:"empty",phon:"*veed*",def:"Sans contenu.",ex:"Un verre vide.",level:4,cat:"adjectif"},
  {fr:"vie",en:"life",phon:"*vee*",def:"Existence.",ex:"La vie est belle.",level:3,cat:"nom"},
  {fr:"vieux",en:"old",phon:"*vyuh*",def:"Âgé.",ex:"Un vieux monsieur.",level:2,cat:"adjectif"},
  {fr:"ville",en:"town / city",phon:"*veel*",def:"Agglomération.",ex:"La ville de Paris.",level:2,cat:"lieu"},
  {fr:"vin",en:"wine",phon:"*van*",def:"Boisson alcoolisée.",ex:"Un verre de vin.",level:2,cat:"aliment"},
  {fr:"visite",en:"visit",phon:"*vee-ZEET*",def:"Action de rendre visite.",ex:"Faire une visite.",level:3,cat:"nom"},
  {fr:"voilà",en:"there is / here is",phon:"*vwa-LA*",def:"Présentation.",ex:"Voilà le problème.",level:2,cat:"adverbe"},
  {fr:"voisin",en:"neighbor (male)",phon:"*vwa-ZAN*",def:"Personne proche.",ex:"Mon voisin est sympa.",level:2,cat:"personne"},
  {fr:"voisine",en:"neighbor (female)",phon:"*vwa-ZEEN*",def:"Femme proche.",ex:"Ma voisine m'aide.",level:2,cat:"personne"},
  {fr:"voiture",en:"car",phon:"*vwa-TEWR*",def:"Véhicule automobile.",ex:"Une voiture neuve.",level:2,cat:"objet"},
  {fr:"voir",en:"to see",phon:"*vwar*",def:"Percevoir par la vue.",ex:"Je vois bien.",level:2,cat:"verbe"},
  {fr:"vouloir",en:"to want",phon:"*voo-LWAHR*",def:"Avoir la volonté.",ex:"Je veux apprendre.",level:2,cat:"verbe"},
  {fr:"vous",en:"you (formal/plural)",phon:"*voo*",def:"Pronom sujet.",ex:"Vous êtes gentil.",level:1,cat:"pronom"},
  {fr:"vrai",en:"true",phon:"*vray*",def:"Conforme à la réalité.",ex:"C'est vrai.",level:2,cat:"adjectif"},
  {fr:"week-end",en:"weekend",phon:"*week-end*",def:"Samedi et dimanche.",ex:"Bon week-end !",level:3,cat:"temps"},
  {fr:"y",en:"there",phon:"*ee*",def:"Pronom adverbial.",ex:"J'y vais.",level:3,cat:"pronom"},
  {fr:"zoo",en:"zoo",phon:"*zo*",def:"Parc animalier.",ex:"Aller au zoo.",level:4,cat:"lieu"}
];