// BDDlexique.js — Français Master
// 150 mots avec phonétique pour anglophones 40+
// Format : {fr, en, phon, def, ex, level, cat}

const LEXIQUE_BDD = [
{fr:“bonjour”,en:“good morning / hello”,phon:”*bon-ZHOOR*”,def:“Formule de salutation utilisée le matin et la journée.”,ex:“Bonjour, Madame Dupont.”,level:1,cat:“salutation”},
{fr:“bonsoir”,en:“good evening”,phon:”*bon-SWAHR*”,def:“Salutation utilisée l’après-midi et le soir.”,ex:“Bonsoir, comment allez-vous ?”,level:1,cat:“salutation”},
{fr:“au revoir”,en:“goodbye”,phon:”*oh ruh-VWAHR*”,def:“Formule de départ standard.”,ex:“Au revoir et à bientôt !”,level:1,cat:“salutation”},
{fr:“bonne nuit”,en:“good night”,phon:”*bon NUEE*”,def:“Souhait avant de dormir.”,ex:“Bonne nuit, dormez bien.”,level:1,cat:“salutation”},
{fr:“enchanté”,en:“nice to meet you (homme)”,phon:”*on-shon-TAY*”,def:“Dit par un homme lors d’une présentation.”,ex:“Je m’appelle Pierre, enchanté.”,level:1,cat:“présentation”},
{fr:“enchantée”,en:“nice to meet you (femme)”,phon:”*on-shon-TAY*”,def:“Dite par une femme lors d’une présentation.”,ex:“Je m’appelle Marie, enchantée.”,level:1,cat:“présentation”},
{fr:“je m’appelle”,en:“my name is”,phon:”*zhuh ma-PEL*”,def:“Se présenter en donnant son nom.”,ex:“Je m’appelle John Smith.”,level:1,cat:“présentation”},
{fr:“je viens de”,en:“I come from”,phon:”*zhuh VYAN duh*”,def:“Indiquer son pays ou ville d’origine.”,ex:“Je viens d’Irlande.”,level:1,cat:“présentation”},
{fr:“j’habite à”,en:“I live in”,phon:”*zha-BEET ah*”,def:“Indiquer où l’on réside.”,ex:“J’habite à Craon, dans la Vienne.”,level:1,cat:“présentation”},
{fr:“retraité”,en:“retired (homme)”,phon:”*ruh-treh-TAY*”,def:“Personne qui a cessé de travailler.”,ex:“Mon mari est retraité.”,level:1,cat:“présentation”},
{fr:“s’il vous plaît”,en:“please (formel)”,phon:”*seel voo PLEH*”,def:“Formule de politesse pour demander quelque chose.”,ex:“Un café, s’il vous plaît.”,level:1,cat:“politesse”},
{fr:“merci beaucoup”,en:“thank you very much”,phon:”*mair-SEE bo-KOO*”,def:“Remerciement chaleureux.”,ex:“Merci beaucoup pour votre aide.”,level:1,cat:“politesse”},
{fr:“je vous en prie”,en:“you’re welcome (formel)”,phon:”*zhuh voo zon PREE*”,def:“Réponse à un remerciement, forme polie.”,ex:“Je vous en prie, avec plaisir.”,level:1,cat:“politesse”},
{fr:“excusez-moi”,en:“excuse me (formel)”,phon:”*ek-skew-zay-MWAH*”,def:“S’excuser ou attirer l’attention poliment.”,ex:“Excusez-moi, l’heure s’il vous plaît ?”,level:1,cat:“politesse”},
{fr:“je voudrais”,en:“I would like”,phon:”*zhuh voo-DRAY*”,def:“Formule polie pour exprimer un souhait.”,ex:“Je voudrais un kilo de tomates.”,level:2,cat:“expression”},
{fr:“ça fait combien”,en:“how much is it”,phon:”*sa FAY kom-BYAN*”,def:“Demander le prix total.”,ex:“Ça fait combien en tout ?”,level:2,cat:“expression”},
{fr:“c’est tout”,en:“that’s all”,phon:”*say TOO*”,def:“Indiquer qu’on a fini ses achats.”,ex:“C’est tout, merci Madame.”,level:2,cat:“expression”},
{fr:“c’est trop cher”,en:“it’s too expensive”,phon:”*say troh SHAIR*”,def:“Trouver un prix excessif.”,ex:“C’est trop cher pour moi.”,level:2,cat:“expression”},
{fr:“une tranche”,en:“a slice”,phon:”*oon TRONSH*”,def:“Partie coupée fine.”,ex:“Une tranche de jambon.”,level:2,cat:“quantité”},
{fr:“une livre”,en:“500 grams”,phon:”*oon LEEVR*”,def:“Ancienne mesure valant 500g en France.”,ex:“Une livre de cerises.”,level:2,cat:“quantité”},
{fr:“une douzaine”,en:“a dozen”,phon:”*oon doo-ZEN*”,def:“Douze unités.”,ex:“Une douzaine d’œufs.”,level:2,cat:“quantité”},
{fr:“la boulangerie”,en:“bakery”,phon:”*boo-lan-zhuh-REE*”,def:“Commerce où l’on vend du pain et viennoiseries.”,ex:“La boulangerie du coin.”,level:2,cat:“commerce”},
{fr:“fromage”,en:“cheese”,phon:”*fro-MAHZH*”,def:“Produit laitier fermenté.”,ex:“Du fromage de chèvre.”,level:2,cat:“aliment”},
{fr:“baguette”,en:“baguette”,phon:”*ba-GET*”,def:“Pain long et croustillant, emblème français.”,ex:“Une baguette tradition.”,level:2,cat:“aliment”},
{fr:“une fleur”,en:“a flower”,phon:”*oon FLUHR*”,def:“Partie colorée et parfumée d’une plante.”,ex:“Une belle fleur rouge.”,level:3,cat:“nature”},
{fr:“un arbre”,en:“a tree”,phon:”*uh NAR-bruh*”,def:“Plante ligneuse de grande taille.”,ex:“Un vieil arbre dans le jardin.”,level:3,cat:“nature”},
{fr:“l’herbe”,en:“grass”,phon:”*LAR-buh*”,def:“Plantes basses qui couvrent le sol.”,ex:“L’herbe est bien verte.”,level:3,cat:“nature”},
{fr:“une feuille”,en:“a leaf”,phon:”*oon FUH-yuh*”,def:“Organe vert des plantes.”,ex:“Les feuilles tombent en automne.”,level:3,cat:“nature”},
{fr:“un potager”,en:“vegetable garden”,phon:”*uh po-ta-ZHAY*”,def:“Jardin où l’on cultive des légumes.”,ex:“Mon potager derrière la maison.”,level:3,cat:“nature”},
{fr:“une serre”,en:“greenhouse”,phon:”*oon SAIR*”,def:“Construction vitrée pour cultiver des plantes.”,ex:“Des tomates dans la serre.”,level:3,cat:“nature”},
{fr:“un arrosoir”,en:“watering can”,phon:”*uh na-roz-WAHR*”,def:“Récipient pour arroser les plantes.”,ex:“Remplir l’arrosoir.”,level:3,cat:“outil”},
{fr:“planter”,en:“to plant”,phon:”*plan-TAY*”,def:“Mettre une plante en terre.”,ex:“Je plante des tomates.”,level:3,cat:“verbe”},
{fr:“arroser”,en:“to water”,phon:”*a-roh-ZAY*”,def:“Donner de l’eau aux plantes.”,ex:“Il faut arroser le soir.”,level:3,cat:“verbe”},
{fr:“tailler”,en:“to prune / trim”,phon:”*TIE-yay*”,def:“Couper pour former ou nettoyer.”,ex:“Tailler la haie.”,level:3,cat:“verbe”},
{fr:“récolter”,en:“to harvest”,phon:”*ray-kol-TAY*”,def:“Cueillir les fruits de son travail.”,ex:“Récolter les légumes.”,level:3,cat:“verbe”},
{fr:“faucher”,en:“to mow”,phon:”*foh-SHAY*”,def:“Couper l’herbe ou les céréales.”,ex:“Faucher la pelouse.”,level:3,cat:“verbe”},
{fr:“un voisin”,en:“neighbor (male)”,phon:”*uh vwa-ZAN*”,def:“Personne qui habite à proximité.”,ex:“Mon voisin est très gentil.”,level:4,cat:“social”},
{fr:“une voisine”,en:“neighbor (female)”,phon:”*oon vwa-ZEEN*”,def:“Femme qui habite à proximité.”,ex:“Ma voisine m’aide souvent.”,level:4,cat:“social”},
{fr:“le quartier”,en:“neighborhood”,phon:”*luh kar-TYAY*”,def:“Partie d’une ville, zone résidentielle.”,ex:“Un quartier très calme.”,level:4,cat:“lieu”},
{fr:“une rue”,en:“a street”,phon:”*oon ROO*”,def:“Voie publique dans une ville.”,ex:“La rue principale du village.”,level:4,cat:“lieu”},
{fr:“une impasse”,en:“dead end”,phon:”*oon om-PASS*”,def:“Rue sans issue.”,ex:“J’habite dans une impasse.”,level:4,cat:“lieu”},
{fr:“le bruit”,en:“noise”,phon:”*luh BREE*”,def:“Son désagréable ou fort.”,ex:“Il y a trop de bruit.”,level:4,cat:“sensation”},
{fr:“le calme”,en:“quiet / calm”,phon:”*luh KALM*”,def:“Absence de bruit, tranquillité.”,ex:“Le calme du quartier.”,level:4,cat:“sensation”},
{fr:“emprunter”,en:“to borrow”,phon:”*om-PRON-tay*”,def:“Utiliser temporairement quelque chose.”,ex:“Je peux vous emprunter une échelle ?”,level:4,cat:“verbe”},
{fr:“prêter”,en:“to lend”,phon:”*PRAY-tay*”,def:“Donner temporairement quelque chose.”,ex:“Je vous prête mon livre.”,level:4,cat:“verbe”},
{fr:“désolé”,en:“sorry (male)”,phon:”*day-zo-LAY*”,def:“Exprimer des excuses.”,ex:“Je suis désolé du dérangement.”,level:4,cat:“politesse”},
{fr:“j’adore”,en:“I love”,phon:”*zha-DOR*”,def:“Aimer intensément.”,ex:“J’adore le fromage français.”,level:5,cat:“sentiment”},
{fr:“j’aime bien”,en:“I like”,phon:”*zhem BYAN*”,def:“Éprouver de l’affection, forme modérée.”,ex:“J’aime bien cette région.”,level:5,cat:“sentiment”},
{fr:“je déteste”,en:“I hate”,phon:”*zhuh day-TEST*”,def:“Ne pas aimer du tout.”,ex:“Je déteste le bruit.”,level:5,cat:“sentiment”},
{fr:“je préfère”,en:“I prefer”,phon:”*zhuh pray-FAIR*”,def:“Choisir par goût.”,ex:“Je préfère le thé au café.”,level:5,cat:“sentiment”},
{fr:“j’ai envie de”,en:“I feel like”,phon:”*zha-ay on-VEE duh*”,def:“Fort désir de quelque chose.”,ex:“J’ai envie de dormir.”,level:5,cat:“expression”},
{fr:“ça me tente”,en:“I’m tempted”,phon:”*sa muh TONT*”,def:“Être attiré par quelque chose.”,ex:“Ça me tente beaucoup.”,level:5,cat:“expression”},
{fr:“je rêve de”,en:“I dream of”,phon:”*zhuh REV duh*”,def:“Aspirer à quelque chose.”,ex:“Je rêve de visiter Paris.”,level:5,cat:“sentiment”},
{fr:“la pâtisserie”,en:“pastry shop”,phon:”*pa-tee-suh-REE*”,def:“Commerce de gâteaux et pâtisseries.”,ex:“Une tarte à la pâtisserie.”,level:6,cat:“commerce”},
{fr:“la boucherie”,en:“butcher shop”,phon:”*boo-shuh-REE*”,def:“Commerce de viande.”,ex:“De la viande à la boucherie.”,level:6,cat:“commerce”},
{fr:“la charcuterie”,en:“delicatessen”,phon:”*shar-koo-tuh-REE*”,def:“Commerce de salaison et charcuterie.”,ex:“Du saucisson à la charcuterie.”,level:6,cat:“commerce”},
{fr:“la pharmacie”,en:“pharmacy”,phon:”*far-ma-SEE*”,def:“Commerce de médicaments.”,ex:“À côté de la pharmacie.”,level:6,cat:“commerce”},
{fr:“le tabac-presse”,en:“newsagent/tobacconist”,phon:”*ta-BAK PRESS*”,def:“Commerce typique français : cigarettes, timbres, journaux.”,ex:“Acheter des timbres au tabac-presse.”,level:6,cat:“commerce”},
{fr:“un timbre”,en:“a stamp”,phon:”*uh TAN-bruh*”,def:“Vignette pour affranchir le courrier.”,ex:“Un timbre pour l’étranger.”,level:6,cat:“objet”},
{fr:“lait cru”,en:“raw milk”,phon:”*lay KROO*”,def:“Lait non pasteurisé.”,ex:“Du fromage au lait cru.”,level:6,cat:“aliment”},
{fr:“sans gluten”,en:“gluten-free”,phon:”*SON gloo-TEN*”,def:“Ne contenant pas de gluten.”,ex:“Du pain sans gluten.”,level:6,cat:“aliment”},
{fr:“un ami”,en:“a friend (male)”,phon:”*uh na-MEE*”,def:“Personne liée par l’affection.”,ex:“Mon ami d’enfance.”,level:7,cat:“social”},
{fr:“une amie”,en:“a friend (female)”,phon:”*oon na-MEE*”,def:“Personne liée par l’affection.”,ex:“Mon amie de toujours.”,level:7,cat:“social”},
{fr:“un rendez-vous”,en:“an appointment / a date”,phon:”*uh ron-day-VOO*”,def:“Rencontre fixée d’avance.”,ex:“Un rendez-vous au café.”,level:7,cat:“social”},
{fr:“sortir”,en:“to go out”,phon:”*sor-TEER*”,def:“Quitter son domicile pour s’amuser.”,ex:“Sortir le soir.”,level:7,cat:“verbe”},
{fr:“inviter”,en:“to invite”,phon:”*on-vee-TAY*”,def:“Demander à quelqu’un de venir.”,ex:“Inviter des amis à dîner.”,level:7,cat:“verbe”},
{fr:“retrouver”,en:“to meet up”,phon:”*ruh-troo-VAY*”,def:“Rendez-vous avec quelqu’un connu.”,ex:“On se retrouve demain ?”,level:7,cat:“verbe”},
{fr:“libre”,en:“free / available”,phon:”*LEEB-ruh*”,def:“Disponible, sans occupation.”,ex:“Je suis libre samedi.”,level:7,cat:“état”},
{fr:“occupé”,en:“busy (male)”,phon:”*ok-kew-PAY*”,def:“Ayant une occupation.”,ex:“Je suis occupé demain.”,level:7,cat:“état”},
{fr:“à bientôt”,en:“see you soon”,phon:”*a byan-TOH*”,def:“Prendre congé pour un prochain rendez-vous.”,ex:“Au revoir, à bientôt !”,level:7,cat:“salutation”},
{fr:“il fait beau”,en:“it’s nice weather”,phon:”*eel FAY bo*”,def:“Description d’un temps agréable.”,ex:“Il fait beau, allons nous promener.”,level:8,cat:“météo”},
{fr:“il pleut”,en:“it’s raining”,phon:”*eel PLUH*”,def:“Chute de gouttes d’eau.”,ex:“Il pleut, prenez un parapluie.”,level:8,cat:“météo”},
{fr:“il neige”,en:“it’s snowing”,phon:”*eel NEHZH*”,def:“Chute de neige.”,ex:“Il neige dans le nord.”,level:8,cat:“météo”},
{fr:“il fait du vent”,en:“it’s windy”,phon:”*eel FAY dew VON*”,def:“Présence de vent.”,ex:“Il fait du vent, fermez la porte.”,level:8,cat:“météo”},
{fr:“il fait chaud”,en:“it’s hot”,phon:”*eel FAY sho*”,def:“Température élevée.”,ex:“Il fait chaud, buvez de l’eau.”,level:8,cat:“météo”},
{fr:“il fait froid”,en:“it’s cold”,phon:”*eel FAY FRWAH*”,def:“Température basse.”,ex:“Il fait froid, allumez le chauffage.”,level:8,cat:“météo”},
{fr:“il fait frais”,en:“it’s cool / chilly”,phon:”*eel FAY FRAY*”,def:“Température fraîche.”,ex:“Il fait frais, prenez un pull.”,level:8,cat:“météo”},
{fr:“aujourd’hui”,en:“today”,phon:”*oh-zhoord-DWEE*”,def:“Le jour présent.”,ex:“Aujourd’hui, il fait beau.”,level:8,cat:“temps”},
{fr:“demain”,en:“tomorrow”,phon:”*duh-MAN*”,def:“Le jour suivant.”,ex:“À demain, Madame.”,level:8,cat:“temps”},
{fr:“après-demain”,en:“the day after tomorrow”,phon:”*a-PRAY duh-MAN*”,def:“Deux jours après aujourd’hui.”,ex:“À après-demain !”,level:8,cat:“temps”},
{fr:“au printemps”,en:“in spring”,phon:”*oh PRAN-ton*”,def:“Saison du renouveau, mars à mai.”,ex:“Au printemps, les fleurs éclosent.”,level:8,cat:“saison”},
{fr:“en été”,en:“in summer”,phon:”*on ay-TAY*”,def:“Saison chaude, juin à août.”,ex:“En été, le jardin est beau.”,level:8,cat:“saison”},
{fr:“en automne”,en:“in autumn”,phon:”*on no-TON*”,def:“Saison des feuilles mortes.”,ex:“En automne, les feuilles tombent.”,level:8,cat:“saison”},
{fr:“en hiver”,en:“in winter”,phon:”*on ee-VAIR*”,def:“Saison froide, décembre à février.”,ex:“En hiver, le jardin dort.”,level:8,cat:“saison”},
{fr:“aller”,en:“to go”,phon:”*a-LAY*”,def:“Se déplacer vers un lieu.”,ex:“Je vais au marché.”,level:9,cat:“verbe”},
{fr:“faire”,en:“to do / to make”,phon:”*FAIR*”,def:“Réaliser une action.”,ex:“Je fais mes courses.”,level:9,cat:“verbe”},
{fr:“prendre”,en:“to take”,phon:”*PRON-druh*”,def:“Saisir ou consommer.”,ex:“Je prends le bus.”,level:9,cat:“verbe”},
{fr:“venir”,en:“to come”,phon:”*vuh-NEER*”,def:“Se rendre vers le locuteur.”,ex:“Je viens de France.”,level:9,cat:“verbe”},
{fr:“pouvoir”,en:“can / to be able to”,phon:”*poo-VWAHR*”,def:“Avoir la capacité.”,ex:“Je peux vous aider.”,level:9,cat:“verbe”},
{fr:“vouloir”,en:“to want”,phon:”*voo-LWAHR*”,def:“Avoir le désir.”,ex:“Je veux apprendre.”,level:9,cat:“verbe”},
{fr:“savoir”,en:“to know (facts)”,phon:”*sa-VWAHR*”,def:“Connaître une information ou un fait.”,ex:“Je sais où c’est.”,level:9,cat:“verbe”},
{fr:“connaître”,en:“to know (people/places)”,phon:”*ko-NET-ruh*”,def:“Avoir une relation avec une personne ou un lieu.”,ex:“Je connais Paris.”,level:9,cat:“verbe”},
{fr:“devoir”,en:“must / to have to”,phon:”*duh-VWAHR*”,def:“Être obligé.”,ex:“Je dois partir.”,level:9,cat:“verbe”},
{fr:“comprendre”,en:“to understand”,phon:”*kom-PRON-druh*”,def:“Saisir le sens.”,ex:“Je comprends le français.”,level:9,cat:“verbe”},
{fr:“je ne comprends pas”,en:“I don’t understand”,phon:”*zhuh nuh kom-PRON PAH*”,def:“Indiquer qu’on n’a pas saisi.”,ex:“Je ne comprends pas, pouvez-vous répéter ?”,level:10,cat:“expression”},
{fr:“parlez plus lentement”,en:“speak more slowly”,phon:”*par-LAY plew lon-TUH-mon*”,def:“Demander de ralentir.”,ex:“Parlez plus lentement, s’il vous plaît.”,level:10,cat:“expression”},
{fr:“comment dit-on”,en:“how do you say”,phon:”*ko-MON dee-TON*”,def:“Demander une traduction.”,ex:“Comment dit-on ‘hello’ en français ?”,level:10,cat:“expression”},
{fr:“je cherche mes mots”,en:“I’m looking for my words”,phon:”*zhuh SHAIRSH may MOH*”,def:“Hésiter en parlant.”,ex:“Je cherche mes mots, désolé.”,level:10,cat:“expression”},
{fr:“avec plaisir”,en:“with pleasure”,phon:”*a-vek pleh-ZEER*”,def:“Accepter avec enthousiasme.”,ex:“Avec plaisir, je viendrai.”,level:10,cat:“politesse”},
{fr:“de rien”,en:“you’re welcome (casual)”,phon:”*duh RYAN*”,def:“Réponse légère à un remerciement.”,ex:“De rien, c’était un plaisir.”,level:10,cat:“politesse”},
{fr:“pas de problème”,en:“no problem”,phon:”*pa duh pro-BLEM*”,def:“Rassurer, indiquer que c’est facile.”,ex:“Pas de problème, je peux vous aider.”,level:10,cat:“expression”}

// ── NIVEAU 7 — Les amis & sorties 👫 ──
{fr:“rendez-vous”,en:“appointment / date”,phon:”*ron-day-VOO*”,def:“Rencontre fixée à l’avance.”,ex:“J’ai un rendez-vous à midi.”,level:7,cat:“social”},
{fr:“sortir”,en:“to go out”,phon:”*sor-TEER*”,def:“Quitter son domicile pour une activité.”,ex:“Sortir avec des amis.”,level:7,cat:“verbe”},
{fr:“inviter”,en:“to invite”,phon:”*on-vee-TAY*”,def:“Demander à quelqu’un de venir.”,ex:“Inviter des voisins à dîner.”,level:7,cat:“verbe”},
{fr:“retrouver”,en:“to meet up”,phon:”*ruh-troo-VAY*”,def:“Se rejoindre à un endroit convenu.”,ex:“On se retrouve devant la mairie.”,level:7,cat:“verbe”},
{fr:“libre”,en:“free / available”,phon:”*LEE-bruh*”,def:“Disponible, sans obligation.”,ex:“Je suis libre samedi.”,level:7,cat:“adjectif”},
{fr:“occupé”,en:“busy”,phon:”*o-koo-PAY*”,def:“Qui a quelque chose à faire.”,ex:“Désolé, je suis occupé.”,level:7,cat:“adjectif”},
{fr:“midi”,en:“noon”,phon:”*mee-DEE*”,def:“12 heures, milieu de la journée.”,ex:“On déjeune à midi.”,level:7,cat:“temps”},
{fr:“à bientôt”,en:“see you soon”,phon:”*a byan-TO*”,def:“Formule de départ pour une prochaine rencontre.”,ex:“Au revoir, à bientôt !”,level:7,cat:“salutation”},
{fr:“avec plaisir”,en:“with pleasure”,phon:”*a-vek play-ZEER*”,def:“Accepter avec enthousiasme.”,ex:“Avec plaisir, je viendrai.”,level:7,cat:“politesse”},
{fr:“ça vous dit”,en:“do you fancy / how about”,phon:”*sa voo DEE*”,def:“Proposition informelle.”,ex:“Ça vous dit d’aller au café ?”,level:7,cat:“expression”},

// ── NIVEAU 8 — Le temps & la météo 🌤️ ──
{fr:“il fait beau”,en:“it’s nice weather”,phon:”*eel FAY bo*”,def:“Temps agréable, ensoleillé.”,ex:“Il fait beau, allons nous promener.”,level:8,cat:“météo”},
{fr:“il pleut”,en:“it’s raining”,phon:”*eel PLUH*”,def:“Pluie qui tombe.”,ex:“Il pleut, prenez un parapluie.”,level:8,cat:“météo”},
{fr:“il neige”,en:“it’s snowing”,phon:”*eel NEHZH*”,def:“Chute de neige.”,ex:“Il neige dans le nord.”,level:8,cat:“météo”},
{fr:“il fait du vent”,en:“it’s windy”,phon:”*eel FAY dew VON*”,def:“Vent présent.”,ex:“Il fait du vent, fermez la porte.”,level:8,cat:“météo”},
{fr:“il fait chaud”,en:“it’s hot”,phon:”*eel FAY sho*”,def:“Température élevée.”,ex:“Il fait très chaud aujourd’hui.”,level:8,cat:“météo”},
{fr:“il fait froid”,en:“it’s cold”,phon:”*eel FAY FRWAH*”,def:“Température basse.”,ex:“Il fait froid, mettez un manteau.”,level:8,cat:“météo”},
{fr:“il fait frais”,en:“it’s cool / chilly”,phon:”*eel FAY FRAY*”,def:“Température fraîche, agréable.”,ex:“Il fait frais ce matin.”,level:8,cat:“météo”},
{fr:“au printemps”,en:“in spring”,phon:”*oh PRAN-ton*”,def:“Pendant la saison du printemps.”,ex:“Au printemps, les fleurs éclosent.”,level:8,cat:“saison”},
{fr:“en été”,en:“in summer”,phon:”*on ay-TAY*”,def:“Pendant la saison chaude.”,ex:“En été, on va à la plage.”,level:8,cat:“saison”},
{fr:“en automne”,en:“in autumn”,phon:”*on no-TON*”,def:“Pendant la saison des feuilles mortes.”,ex:“En automne, les feuilles tombent.”,level:8,cat:“saison”},
{fr:“en hiver”,en:“in winter”,phon:”*on ee-VAIR*”,def:“Pendant la saison froide.”,ex:“En hiver, il gèle parfois.”,level:8,cat:“saison”},
{fr:“après-demain”,en:“the day after tomorrow”,phon:”*a-PRAY duh-MAN*”,def:“Deux jours après aujourd’hui.”,ex:“On se voit après-demain.”,level:8,cat:“temps”},

// ── NIVEAU 9 — Les verbes essentiels ⚡ ──
{fr:“je vais”,en:“I go / I am going”,phon:”*zhuh VAY*”,def:“Conjugaison de ‘aller’ au présent.”,ex:“Je vais au marché.”,level:9,cat:“verbe”},
{fr:“je fais”,en:“I do / I make”,phon:”*zhuh FAY*”,def:“Conjugaison de ‘faire’ au présent.”,ex:“Je fais mes courses.”,level:9,cat:“verbe”},
{fr:“je prends”,en:“I take”,phon:”*zhuh PRON*”,def:“Conjugaison de ‘prendre’ au présent.”,ex:“Je prends le bus.”,level:9,cat:“verbe”},
{fr:“je peux”,en:“I can”,phon:”*zhuh PUH*”,def:“Conjugaison de ‘pouvoir’ au présent.”,ex:“Je peux vous aider.”,level:9,cat:“verbe”},
{fr:“je veux”,en:“I want”,phon:”*zhuh VUH*”,def:“Conjugaison de ‘vouloir’ au présent.”,ex:“Je veux du café.”,level:9,cat:“verbe”},
{fr:“je sais”,en:“I know (fact)”,phon:”*zhuh SAY*”,def:“Conjugaison de ‘savoir’ — pour les faits.”,ex:“Je sais où c’est.”,level:9,cat:“verbe”},
{fr:“je connais”,en:“I know (person/place)”,phon:”*zhuh ko-NAY*”,def:“Conjugaison de ‘connaître’ — pour les personnes.”,ex:“Je connais ce village.”,level:9,cat:“verbe”},
{fr:“je dois”,en:“I must”,phon:”*zhuh DWAH*”,def:“Conjugaison de ‘devoir’ — obligation.”,ex:“Je dois partir.”,level:9,cat:“verbe”},
{fr:“vous faites”,en:“you do (formal)”,phon:”*voo FET*”,def:“Conjugaison irrégulière de ‘faire’.”,ex:“Qu’est-ce que vous faites ?”,level:9,cat:“verbe”},
{fr:“pouvez-vous”,en:“can you (formal)”,phon:”*poo-vay VOO*”,def:“Demande polie de capacité.”,ex:“Pouvez-vous répéter ?”,level:9,cat:“expression”},
];
